server:
  servlet:
    context-path: /consultas/api

spring:
  application:
    name: consultas

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

fipe:
  api:
    base-url: https://parallelum.com.br/fipe/api/v1

viacep:
  api:
    base-url: https://viacep.com.br

