# Web Server
server:
  servlet:
    context-path: /consultas/api

spring:
  application:
    name: consultas


fipe:
  api:
    base-url: https://parallelum.com.br/fipe/api/v1

viacep:
  api:
    base-url: https://viacep.com.br


ejc:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}